export const CandidateData = [
  {
    id: 1,
    profile: "https://randomuser.me/api/portraits/men/3.jpg",
    name: "Nitish Soni",
    experience: 2,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "https://www.linkedin.com/in/nitish-soni-ba0085206/",
      twitter: "https://twitter.com/_2nitish6_",
      github: "https://github.com/NitishSoni-1726",
    },
    saved: false,
  },
  {
    id: 2,
    profile: "https://randomuser.me/api/portraits/men/2.jpg",
    name: "Jasprit Singh",
    experience: 3,
    tags: "DevOps Engineer",
    location: "Hyderabad",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 3,
    profile: "https://randomuser.me/api/portraits/men/1.jpg",
    name: "Kshitij Agrawal",
    experience: 1,
    tags: "Software Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 4,
    profile: "https://randomuser.me/api/portraits/men/4.jpg",
    name: "Pushp Raj",
    experience: 2,
    tags: "Acedemic Counselor",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 5,
    profile: "https://randomuser.me/api/portraits/men/5.jpg",
    name: "Dharma",
    experience: 0,
    tags: "Front-End Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 6,
    profile: "https://randomuser.me/api/portraits/women/6.jpg",
    name: "Anamika Paul",
    experience: 1,
    tags: "Food Quality Testing",
    location: "Tezpur",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 7,
    profile: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "Ajju Alam",
    experience: 2,
    tags: "Lawyer",
    location: "Tezpur",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 8,
    profile: "https://randomuser.me/api/portraits/women/8.jpg",
    name: "Aayushi Jain",
    experience: 2,
    tags: "MBA",
    location: "Tezpur",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 9,
    profile: "https://randomuser.me/api/portraits/women/9.jpg",
    name: "Aisha Sharma",
    experience: 6,
    tags: "Android Development",
    location: "Patna",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 10,
    profile: "https://randomuser.me/api/portraits/men/10.jpg",
    name: "Himanshu Kumar",
    experience: 7,
    tags: "Android Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 11,
    profile: "https://randomuser.me/api/portraits/men/11.jpg",
    name: "Pranay Agrawal",
    experience: 1,
    tags: "Lawyer",
    location: "Guwahati",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 12,
    profile: "https://randomuser.me/api/portraits/women/12.jpg",
    name: "Nidhi Tiwari",
    experience: 8,
    tags: "Fashion Designer",
    location: "Bhubneshwar",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 13,
    profile: "https://randomuser.me/api/portraits/men/13.jpg",
    name: "Ashish Kumar",
    experience: 9,
    tags: "Electrical Engineer",
    location: "Delhi",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 14,
    profile: "https://randomuser.me/api/portraits/women/14.jpg",
    name: "Payal Baul",
    experience: 5,
    tags: "Data Analyst",
    location: "Kolkata",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 15,
    profile: "https://randomuser.me/api/portraits/women/15.jpg",
    name: "Pratiksha Gogoi",
    experience: 4,
    tags: "Graphics Designer",
    location: "Guwahati",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 16,
    profile: "https://randomuser.me/api/portraits/men/16.jpg",
    name: "Hrithik Patodia",
    experience: 4,
    tags: "Full Stack Developer",
    location: "Jaipur",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 17,
    profile: "https://randomuser.me/api/portraits/women/17.jpg",
    name: "Puja Sarda",
    experience: 2,
    tags: "Back-end Developer",
    location: "Udaipur",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 18,
    profile: "https://randomuser.me/api/portraits/women/18.jpg",
    name: "Isha Jain",
    experience: 8,
    tags: "Full Stack Developer",
    location: "Udaipur",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 19,
    profile: "https://randomuser.me/api/portraits/women/19.jpg",
    name: "Gauri Ruhal",
    experience: 11,
    tags: "Tech Support",
    location: "Chennai",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 20,
    profile: "https://randomuser.me/api/portraits/women/20.jpg",
    name: "Sushree Ananya Nayak",
    experience: 15,
    tags: "DevOps Engineer",
    location: "Bhubneshwar",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 21,
    profile: "https://randomuser.me/api/portraits/men/21.jpg",
    name: "N Satwik Kumar Chaudhary",
    experience: 8,
    tags: "Back-end Developer",
    location: "Chennai",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 22,
    profile: "https://randomuser.me/api/portraits/men/22.jpg",
    name: "Chandan Jhawar",
    experience: 0,
    tags: "Graphics Designer",
    location: "Mumbai",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 23,
    profile: "https://randomuser.me/api/portraits/men/23.jpg",
    name: "Tarun Bhatti",
    experience: 0,
    tags: "Accountant",
    location: "Nagaon",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 24,
    profile: "https://randomuser.me/api/portraits/men/24.jpg",
    name: "Vinit Bothra",
    experience: 4,
    tags: "Accountant",
    location: "Jaipur",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 25,
    profile: "https://randomuser.me/api/portraits/women/25.jpg",
    name: "Kaveri Sharma",
    experience: 4,
    tags: "Event Manager",
    location: "Mumbai",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 26,
    profile: "https://randomuser.me/api/portraits/women/26.jpg",
    name: "Priya Baruah",
    experience: 3,
    tags: "Hotel Management",
    location: "Pune",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 27,
    profile: "https://randomuser.me/api/portraits/women/27.jpg",
    name: "Mridushmita Baruah",
    experience: 7,
    tags: "Event Manager",
    location: "Delhi",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 28,
    profile: "https://randomuser.me/api/portraits/men/28.jpg",
    name: "Atul Sharma",
    experience: 6,
    tags: "Electrical Engineer",
    location: "Patna",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 29,
    profile: "https://randomuser.me/api/portraits/men/29.jpg",
    name: "Sahil Das",
    experience: 9,
    tags: "Security Management",
    location: "Pune",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 30,
    profile: "https://randomuser.me/api/portraits/men/30.jpg",
    name: "Tanmay Bhat",
    experience: 10,
    tags: "Content Writter",
    location: "Goa",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 31,
    profile: "https://randomuser.me/api/portraits/women/31.jpg",
    name: "Kashvi Hiranandani",
    experience: 11,
    tags: "Social Media Manager",
    location: "Surat",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 32,
    profile: "https://randomuser.me/api/portraits/men/32.jpg",
    name: "Akshay Rana",
    experience: 12,
    tags: "Content Writter",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 33,
    profile: "https://randomuser.me/api/portraits/women/33.jpg",
    name: "Sonam Bajwa",
    experience: 4,
    tags: "Photographar",
    location: "Amritsar",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 34,
    profile: "https://randomuser.me/api/portraits/men/34.jpg",
    name: "Atul Bhuyan",
    experience: 1,
    tags: "Photographar",
    location: "Pune",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 35,
    profile: "https://randomuser.me/api/portraits/men/35.jpg",
    name: "Tarun Kothari",
    experience: 1,
    tags: "Bank Management",
    location: "Hyderabad",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 36,
    profile: "https://randomuser.me/api/portraits/men/36.jpg",
    name: "Kunal Jain",
    experience: 0,
    tags: "Accountant",
    location: "Delhi",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 37,
    profile: "https://randomuser.me/api/portraits/women/37.jpg",
    name: "Raksha Jalan",
    experience: 0,
    tags: "Bank Management",
    location: "Ahemdabad",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 38,
    profile: "https://randomuser.me/api/portraits/women/38.jpg",
    name: "Vridhi Jain",
    experience: 12,
    tags: "Aerospace Engineer",
    location: "Lucknow",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 39,
    profile: "https://randomuser.me/api/portraits/women/39.jpg",
    name: "Mariya Begum",
    experience: 12,
    tags: "Social Media Manager",
    location: "Mumbai",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
  {
    id: 40,
    profile: "https://randomuser.me/api/portraits/men/40.jpg",
    name: "Paras Gupta",
    experience: 11,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
    saved: false,
  },
];
