export const CandidateData = [
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 2,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "https://github.com/NitishSoni-1726",
    },
  },
  {
    profile: "Link",
    name: "Jasprit Singh",
    experience: 3,
    tags: "DevOps Engineer",
    location: "Hyderabad",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Kshitij Agrawal",
    experience: 1,
    tags: "Software Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Pushp Raj",
    experience: 2,
    tags: "Acedemic Counselor",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Dharma",
    experience: 0,
    tags: "Front-End Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Porus Singh",
    experience: 1,
    tags: "Food Quality Testing",
    location: "Tezpur",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Ajju Alam",
    experience: 2,
    tags: "Lawyer",
    location: "Tezpur",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 2,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 6,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 7,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 1,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 8,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 9,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 5,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 4,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 4,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 2,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 8,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 11,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 15,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 8,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 0,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 0,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 4,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 4,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 3,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 7,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 6,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 9,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 10,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 11,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 12,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 4,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 1,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 1,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 0,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 0,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 12,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 12,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 11,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 13,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 2,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 4,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
  {
    profile: "Link",
    name: "Nitish Soni",
    experience: 3,
    tags: "Full Stack Developer",
    location: "Bangalore",
    social: {
      instagram: "link",
      linkedin: "Link",
      twitter: "link",
      github: "link",
    },
  },
];
